# Generated by Django 2.2.3 on 2019-07-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.PositiveIntegerField()),
                ('town', models.TextField()),
                ('street', models.TextField()),
                ('building', models.TextField()),
                ('appartement', models.IntegerField()),
                ('name', models.TextField()),
                ('birth_date', models.DateField()),
                ('gender', models.TextField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='collection.Collection')),
                ('relatives', models.ManyToManyField(to='collection.Citizen')),
            ],
        ),
    ]
