# Generated by Django 2.2.3 on 2019-08-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190817_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='appartement',
            field=models.PositiveIntegerField(),
        ),
    ]
