# Generated by Django 2.2.3 on 2019-08-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190817_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='appartement',
            new_name='apartment',
        ),
    ]
